name: Test CI Reusable workflow

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  playwright-ui-test:
    uses: msanthosh-murugesan/react-node-cicd/.github/workflows/reusable-workflow1.yml@workflow
    secrets: inherit
