name: Context

on:
  pull_request

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Adding conditio to test
        if: github.event.pull_request.base.ref == 'main'
        run: echo "Success"

  two:
      runs-on: ubuntu-latest
      needs: one
      if: github.event.pull_request.merged
      steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
          run: echo "$GITHUB_CONTEXT"
  
        - name: Adding conditio to test
          if: github.event.pull_request.base.ref == 'main'
          run: echo "Success"  

  three:
    runs-on: ubuntu-latest
    needs: two
    if: always()
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Adding conditio to test
        if: github.event.pull_request.base.ref == 'main'
        run: echo "Success" 

  four:
    runs-on: ubuntu-latest
    needs: three
    if: always() && !github.event.pull_request.merged
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Adding conditio to test
        if: github.event.pull_request.base.ref == 'main'
        run: echo "Success"         
