name: Context

on:
  pull_request

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Adding conditio to test
        if: github.event.pull_request.base.ref == 'main'
        run: echo "Success"
