name: Checking default branch for custom workflow run

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        type: choice
        options:
          - main

      environment:
        description: "Project Environment"
        required: false
        default: "staging"
        type: choice
        options:
          - staging
          - live

      migrate:
        description: "Migrate to default?"
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: ${{ inputs.environment == 'live' && 'production' || 'staging' }}-${{ inputs.migrate && 'deploy' || 'non-default-deploy' }}
    steps:
      - name: Greetings
        run: echo "Hello Success"