name: Fetching commits

on:
  pull_request:
      types: [opened, synchronize]
  push:  
    
jobs:
  commits:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Greetings
        run: echo "Hello Success"

      - name: Checkout with minimal depth
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Used to perform unshallow fetch for SonarQube and unit tests diff-tree
      - name: Fetch range of commits
        run: |
          base_sha=${{ github.event.pull_request.base.sha }}
          head_sha=${{ github.event.pull_request.head.sha }}
          git fetch origin "$base_sha" "$head_sha"
          commit_count=$(git rev-list --count "$base_sha..$head_sha")
          echo "Fetch depth is $commit_count"
          git fetch --depth="$commit_count"  