name: Job name testing based on inputs condition

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Project Environment"
        required: false
        default: "staging"
        type: choice
        options:
          - staging
          - live

      migrate:
        description: "Migrate to default?"
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: ${{ inputs.environment == 'live' && 'production' || 'staging' }}-${{ inputs.migrate && 'deploy' || 'non-default-deploy' }}
    steps:
      - name: Greetings
        id: deployer-label
        run: |
          DEPLOYER=$(echo "$ACTOR" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9_-')
          echo "deployer=$DEPLOYER" >> "$GITHUB_OUTPUT"
          echo "label=deployer=$DEPLOYER" >> "$GITHUB_OUTPUT"

      - name: Test
        run: |
          echo ${{ steps.deployer-label.outputs.deployer }}
          echo ${{ steps.deployer-label.outputs.label }}
